version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '13:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        dependency-type: 'development'
        patterns:
          - '*'
      production-dependencies:
        dependency-type: 'production'
        patterns:
          - '*'
    labels:
      - 'dependencies'
      - 'npm'
    versioning-strategy: 'auto'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore(dev)'
      include: 'scope'
    pull-request-branch-name:
      separator: '-'
    reviewers:
      - 'reinaldosimoes'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
