name: Package and Release

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'src/**'
      - 'rollup.config.mjs'
      - 'tsconfig.json'

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: v${{ github.ref_name }}
          tag_name: v${{ github.ref_name }}
          body: |
            ## What's Changed

            ### Features
            - Add new features

            ### Bug Fixes
            - Fix bugs

            ### Dependencies
            - Update dependencies

            ### Documentation
            - Update documentation

            ### Chores
            - Maintenance tasks
          draft: false
          prerelease: false
          generate_release_notes: true
